name: Version
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  code_checks:
    name: Code checks
    if: "!contains(github.event.head_commit.message, 'chore: version packages')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
      - uses: ./.github/actions/code-checks

  version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: version packages')"
    needs: [code_checks]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
      - run: npm ci
      - uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          commitMode: "github-api"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
